version: '2'

services:

  slg-db-dev:
    image: postgres:12.6
    container_name: slg-db-dev
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data

  slg-redis-dev:
    image: 'bitnami/redis:latest'
    container_name: slg-redis-dev
    mem_limit: 256m
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379