# Swagger documentation : https://swagger.io/docs/specification/basic-structure/
openapi: '3.0.2'
info:
  title: SLG Tools 
  version: '1.0'
servers:
  - url: https://slg-app.herokuapp.com/api

paths:

  /cars:
    get:
      description: This is a temporary test path
      responses:
        '200':
          description: Do not use
      tags:
        - "cars"
