# Swagger documentation : https://swagger.io/docs/specification/basic-structure/
openapi: '3.0.2'
info:
  title: SLG Tools 
  version: '1.0'
servers:
  - url: https://slg-app.herokuapp.com/api

paths:
  /bus:
    get:
      description: retrieve a list of all busses
      responses:
        '200':
          description: OK
      tags:
        - "bus"

    delete:
      description: remove an existing bus 
      responses:
        '200':
          description: OK
      tags:
        - "bus"

    options:
      description: d
      responses:
        '200':
          description: OK
      tags:
        - "bus"

  /cars:
    get:
      description:  retrieve a list of all cars
      responses:
        '200':
          description: OK
      tags:
        - "cars"

    post:
      description: Add a new car
      responses:
        '200':
          description: OK
      tags:
        - "cars"

    delete:
      description: Remove a specific car
      responses:
        '200':
          description: OK
      tags:
        - "cars"

    patch:
      description: update a car
      responses:
        '200':
          description: OK
      tags:
        - "cars"
