name: Continous Integration
on: 
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'

env:
  node-version: 14.15.1
      
jobs:
  unit-tests-frontend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node ${{ env.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.node-version }}
        - name: npm install
          working-directory: ./frontend
          run: |
            npm install
        - name: run tests
          working-directory: ./frontend
          run: |
            npm run test:unit:headless
  
  unit-tests-backend:
      runs-on: ubuntu-latest
      env:
        JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node ${{ env.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.node-version }}
        - name: npm install
          working-directory: ./backend
          run: |
            npm install
        - name: run tests
          working-directory: ./backend
          run: |
            npm run test
  
  build-to-Heroku:
    runs-on: ubuntu-latest
    needs: [unit-tests-frontend, unit-tests-backend]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: npm install
        working-directory: ./
        run: |
          cd ./backend && npm install
          cd ../frontend && npm install
      - name: build frontend & move to backend
        working-directory: ./frontend
        run: |
          npm run build --prod
          mkdir ../backend/public
          mv ./dist ../backend/public
      - name: replace backend .gitignore 
        working-directory: ./
        run: |
          rm ./backend/.gitignore
          cp .gitignore ./backend
          
      - name: Commit changes
        working-directory: ./
        run: |
          git config --global user.name "MMichotte"
          git config --global user.email "martin.michotte@gmail.com"
          git add .
          git commit -m "passed tests & build"
    
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "slg-app"
          heroku_email: "martin.michotte@gmail.com"
          appdir: "backend"
        env:
          HD_NODE_ENV: "prod"
          HD_JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
          HD_TOKEN_EXPIRATION: "48h"
          HD_DATABASE_URL: ${{secrets.RPI_DB}}