name: Add new US's to Trello

on:
  push:
    #paths:
    #  - 'docs/wiki/**'

jobs:
  add-trello-card:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: clone US-to-TrelloCard repository
      uses: actions/checkout@v2
      with:
        repository: MMichotte/US-to-TrelloCard
    
    - name: ls
      run: |
        ls
      