name: Add new US's to Trello

on:
  push:
    #paths:
    #  - 'docs/wiki/**'

jobs:
  add-trello-card:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: clone US-to-TrelloCard repository
      run: |
        git clone https://github.com/MMichotte/US-to-TrelloCard
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: instal python dependencies 
      run : |
        pip install --upgrade pip
        pip install -r US-to-TrelloCard/requirements.txt
        pip freeze

    - name: add .env
      run: |
        cd US-to-TrelloCard
        touch .env
        echo "API_KEY = ${{ secrets.TRELLO_API_KEY }}" >> .env 
        echo "OAUTH_TOKEN = ${{ secrets.TRELLO_AUTH_KEY}}" >> .env 
        echo "BOARD_NAME = \"SLG_APP\"" >> .env 
        echo "LIST_NAME = \"To Do\"" >> .env 
        cat .env
              
    - name: add new cards to trello
      run: |
        for file in ./docs/wiki/User-Stories/*; \
        do ls && python3 US-to-TrelloCard/src/addTrelloCards.py "$file"; \
        done
      