name: Add new US's to Trello

on:
  push:
    paths:
      - 'docs/wiki/User-Stories/**'

jobs:
  add-trello-card:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: installing tools
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install wget
        sudo apt-get install unzip

    - name: download latest US-to-TrelloCard release 
      run: |
        wget https://github.com/$(wget https://github.com/MMichotte/US-to-TrelloCard/releases/latest -O - | egrep '/.*/.*/.*zip' -o)
        unzip *.zip -d ./
        rm -f *.zip
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: instal python dependencies 
      run : |
        pip install --upgrade pip
        pip install -r US-to-TrelloCard/requirements.txt
        pip freeze

    - name: add .env
      run: |
        cd US-to-TrelloCard
        touch .env
        echo "API_KEY = ${{ secrets.TRELLO_API_KEY }}" >> .env 
        echo "OAUTH_TOKEN = ${{ secrets.TRELLO_AUTH_KEY}}" >> .env 
        echo "BOARD_NAME = \"SLG_APP\"" >> .env 
        echo "LIST_NAME = \"To Do\"" >> .env 
        echo "LABELS = \"[US]\"" >> .env 
              
    - name: add new cards to trello
      run: |
        for file in ./docs/wiki/User-Stories/*.md; \
        do python3 US-to-TrelloCard/src/add_trello_cards.py -F "$file"; \
        done
      